services:
  web:
    build: . 
    command: npm run start:docker
    ports:
      - "3002:3002"
    depends_on:
      - db
    environment:
      - PORT=3002
      - HOSTDB=localhost
      - PORTDB=5432
      - USERDB=clotilde
      - PASSWORDDB=motdepasse123
      - DBNAME=GestionDon
      - JWT_SECRET=MaCleSecreteSuperSecure123!
      - PEPPER=MonPoivreSecretPourLesPasswords456!

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${USERDB}
      POSTGRES_PASSWORD: ${PASSWORDDB}
      POSTGRES_DB: ${DBNAME}
    ports:
      - "5432:5432"  
